id: eb0c4a7c35a34c31abbd3c3e2c6ec623
initial_creation_type: ocr
source_metadata:
  volumes:
    cb501fcd94134d7e87601108561b7272:
      base_file: v106.txt
      image_group_id: I1PD95952
      title: དེ་ཁོ་ན་ཉིད་བསྡུས་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1891
      volume_number: 107
